Repository kptdev/kpt, pull requests merged in 2021-05, with the labels that each got.

#1898 make eval to use kpt container & exec runtime
  e2e/testdata/fn-eval/missing-fn-config/.expected/config.yaml
  e2e/testdata/fn-eval/missing-fn-image/.expected/config.yaml
  internal/fnruntime/container.go
  internal/fnruntime/exec.go
  thirdparty/kyaml/runfn/runfn.go
  thirdparty/kyaml/runfn/runfn_test.go
Labels: area/hydrate

#1896 `kpt fn render` ensures validators don't mutate resources
  e2e/testdata/fn-render/validate-generated-resource/Kptfile
  e2e/testdata/fn-render/validator-mutates-resources/.krmignore
  e2e/testdata/fn-render/validator-mutates-resources/Kptfile
  e2e/testdata/fn-render/validator-mutates-resources/resources.yaml
  internal/cmdrender/executor.go
Labels: area/hydrate

#1944 Fn render reference
  commands/fncmd.go
  internal/cmdexport/cmdexport.go
  internal/cmdrender/cmd.go
  internal/docs/generated/fndocs/docs.go
  internal/docs/generated/pkgdocs/docs.go
  scripts/generate_site_sidebar/sidebar_template.md
  site/reference/fn/render/README.md
  site/sidebar.md
  thirdparty/cmdconfig/commands/cmdeval/cmdeval.go
Labels: area/hydrate, documentation

#2103 Update installation pages with new version of kpt
  site/installation/README.md
Labels: documentation
