Repository kptdev/kpt, pull requests merged in 2021-04, with the labels that each got.

#1646 update e2e driver to support fn eval tests
  e2e/e2e_docker_test.go
  e2e/testdata/fn-eval/eval-with-simple-function/.expected/config.yaml
  e2e/testdata/fn-eval/eval-with-simple-function/.expected/diff.patch
  e2e/testdata/fn-eval/eval-with-simple-function/.krmignore
  e2e/testdata/fn-eval/eval-with-simple-function/resources.yaml
  pkg/test/runner/config.go
  pkg/test/runner/runner.go
Labels: area/hydrate

#1694 fix edge case for `fn render` where resource filename starts with pkg name
  e2e/testdata/fn-render/resource-has-pkgname-prefix/.expected/config.yaml
  e2e/testdata/fn-render/resource-has-pkgname-prefix/.expected/diff.patch
  e2e/testdata/fn-render/resource-has-pkgname-prefix/.krmignore
  e2e/testdata/fn-render/resource-has-pkgname-prefix/Kptfile
  e2e/testdata/fn-render/resource-has-pkgname-prefix/mysql/Kptfile
  e2e/testdata/fn-render/resource-has-pkgname-prefix/mysql/mysql-deployment.yaml
  e2e/testdata/fn-render/resource-has-pkgname-prefix/wordpress-deployment.yaml
  internal/pipeline/executor.go
Labels: area/hydrate

#1710 Cli Usability: Cleanup fn commands and make dir optional
  commands/fncmd.go
  internal/cmdexport/cmdexport.go
  internal/cmdfndoc/cmdfndoc.go
  internal/cmdrender/cmd.go
  internal/cmdrender/executor.go
  internal/cmdrender/pipeline_function.go
  internal/cmdrender/pipeline_function_test.go
  internal/cmdrender/runtime/container.go
  internal/cmdrender/runtime/container_test.go
  internal/docs/generated/pkgdocs/docs.go
  site/reference/pkg/tree/README.md
  thirdparty/cmdconfig/commands/cmdeval/cmdeval.go
  thirdparty/cmdconfig/commands/cmdeval/cmdeval_test.go
  thirdparty/cmdconfig/commands/cmdsink/cmdsink.go
  thirdparty/cmdconfig/commands/cmdsink/cmdsink_test.go
  thirdparty/cmdconfig/commands/cmdsource/cmdsource.go
  thirdparty/cmdconfig/commands/cmdsource/cmdsource_test.go
  thirdparty/cmdconfig/commands/cmdtree/cmdtree.go
Labels: area/hydrate, cleanup, p1, size/M, triaged, ux impact

#1745 Makefile target to flush kpt fn cache
  Makefile
Labels: area/hydrate

#1634 improve error handling in `fn render` command
  commands/commands.go
  commands/fncmd.go
  internal/cmdrender/cmd.go
  internal/cmdrender/executor.go
  internal/cmdrender/pipeline_function.go
  internal/cmdrender/runtime/container.go
  internal/cmdrender/runtime/container_test.go
  internal/errors/errors.go
  internal/pkg/pkg.go
  internal/printer/printer.go
  internal/types/types.go
  internal/util/cmdutil/cmdutil.go
  main.go
  pkg/test/runner/config.go
  pkg/test/runner/runner.go
  run/run.go
Labels: area/hydrate

#1740 Include Kptfiles and function configs in tree cmd
  go.mod
  go.sum
  thirdparty/cmdconfig/commands/cmdtree/cmdtree.go
  thirdparty/cmdconfig/commands/cmdtree/cmdtree_test.go
  thirdparty/cmdconfig/commands/cmdtree/tree.go
Labels: area/pkg, cleanup, p1, size/M, triaged, ux impact

#1768 one installation page
  scripts/generate_site_sidebar/sidebar_template.md
  site/installation/README.md
  site/installation/binaries/README.md
  site/installation/docker/README.md
  site/installation/gcloud/README.md
  site/installation/homebrew/README.md
  site/installation/source/README.md
  site/sidebar.md
Labels: documentation

#1823 added code blocks
  package-examples/helloworld-kustomize/README.md
  package-examples/helloworld-set/README.md
  package-examples/helloworld-tshirt/README.md
  package-examples/helloworld/README.md
  package-examples/pipeline-validate/README.md
  package-examples/wordpress/README.md
Labels: documentation
