Repository kptdev/kpt, pull requests merged in 2021-03, with the labels that each got.

#1534 Make DIR optional for pkg commands and cleanup
  internal/cmddesc/cmddesc.go
  internal/cmddiff/cmddiff.go
  internal/cmdget/cmdget.go
  internal/cmdget/cmdget_test.go
  internal/cmdinit/cmdinit.go
  internal/cmdinit/cmdinit_test.go
  internal/cmdupdate/cmdupdate.go
  internal/cmdupdate/cmdupdate_test.go
  internal/pkg/pkg.go
  internal/pkg/pkg_test.go
  site/reference/pkg/desc/README.md
  site/reference/pkg/diff/README.md
  site/reference/pkg/get/README.md
  site/reference/pkg/init/README.md
  site/reference/pkg/sidebar.md
  site/reference/pkg/sync/README.md
  site/reference/pkg/sync/set/README.md
  site/reference/pkg/tree/README.md
  site/reference/pkg/update/README.md
Labels: area/pkg, p1, ux impact

#1483 implement pipeline run
  Makefile
  commands/fncmd.go
  e2e/e2e_docker_test.go
  internal/pipeline/cmd.go
  internal/pipeline/executor.go
  internal/pipeline/executor_test.go
  internal/pipeline/fn.go
  internal/pipeline/pipeline.go
  internal/pipeline/pipeline_function.go
  internal/pipeline/pipeline_function_test.go
  internal/pipeline/testdata/pkg-with-basicpipeline/.expected/config.yaml
  internal/pipeline/testdata/pkg-with-basicpipeline/.expected/diff.patch
  internal/pipeline/testdata/pkg-with-basicpipeline/configs/Kptfile
  internal/pipeline/testdata/pkg-with-basicpipeline/configs/resources.yaml
  internal/pipeline/testdata/pkg-with-fnconfig/.expected/config.yaml
  internal/pipeline/testdata/pkg-with-fnconfig/.expected/diff.patch
  internal/pipeline/testdata/pkg-with-fnconfig/configs/Kptfile
  internal/pipeline/testdata/pkg-with-fnconfig/configs/db/Kptfile
  internal/pipeline/testdata/pkg-with-fnconfig/configs/db/resources.yaml
  internal/pipeline/testdata/pkg-with-fnconfig/configs/labelconfig.yaml
  internal/pipeline/testdata/pkg-with-fnconfig/configs/resources.yaml
  internal/pipeline/testdata/pkg-with-generator/.expected/config.yaml
  internal/pipeline/testdata/pkg-with-generator/.expected/diff.patch
  internal/pipeline/testdata/pkg-with-generator/configs/Kptfile
  internal/pipeline/testdata/pkg-with-generator/configs/db/Kptfile
  internal/pipeline/testdata/pkg-with-generator/configs/db/resources.yaml
  internal/pipeline/testdata/pkg-with-generator/configs/resources.yaml
  internal/pipeline/testdata/pkg-with-invalidconfigs/configfilenotfound/.expected/config.yaml
  internal/pipeline/testdata/pkg-with-invalidconfigs/configfilenotfound/.krmignore
  internal/pipeline/testdata/pkg-with-invalidconfigs/configfilenotfound/Kptfile
  internal/pipeline/testdata/pkg-with-invalidconfigs/configfilenotfound/resources.yaml
  internal/pipeline/testdata/pkg-with-invalidconfigs/multipleconfigs/.expected/config.yaml
  internal/pipeline/testdata/pkg-with-invalidconfigs/multipleconfigs/.krmignore
  internal/pipeline/testdata/pkg-with-invalidconfigs/multipleconfigs/Kptfile
  internal/pipeline/testdata/pkg-with-invalidconfigs/multipleconfigs/configmap.yaml
  internal/pipeline/testdata/pkg-with-invalidconfigs/multipleconfigs/resources.yaml
  internal/pipeline/testdata/pkg-with-krmignore/.expected/config.yaml
  internal/pipeline/testdata/pkg-with-krmignore/.krmignore
  internal/pipeline/testdata/pkg-with-krmignore/Kptfile
  internal/pipeline/testdata/pkg-with-krmignore/resources.yaml
  internal/pipeline/testdata/pkg-with-subpkgs/.expected/config.yaml
  internal/pipeline/testdata/pkg-with-subpkgs/.expected/diff.patch
  internal/pipeline/testdata/pkg-with-subpkgs/configs/Kptfile
  internal/pipeline/testdata/pkg-with-subpkgs/configs/db/Kptfile
  internal/pipeline/testdata/pkg-with-subpkgs/configs/db/resources.yaml
  internal/pipeline/testdata/pkg-with-subpkgs/configs/resources.yaml
  internal/pipeline/testdata/simplepackage/.expected/config.yaml
  internal/pipeline/testdata/simplepackage/.expected/diff.patch
  internal/pkg/pkg.go
  internal/pkg/pkg_test.go
  pkg/api/kptfile/v1alpha2/types.go
  pkg/test/runner/config.go
  pkg/test/runner/runner.go
Labels: area/hydrate

#1566 Migrate dockerfile to release directory
  Makefile
  release/Dockerfile
  release/README.md
  release/tag/cloudbuild.yaml
Labels: cleanup

#1595 Fix Dockerfile Location
  release/branch/cloudbuild.yaml
Labels: bug

#1620 Fix GoReleaser release publish owner
  release/README.md
  release/tag/goreleaser.yaml
Labels: area/release, bug
