Repository kptdev/kpt, pull requests merged in 2021-02, with the labels that each got.

#1425 Adds RBAC error during apply end-to-end test case
  e2e/live/end-to-end-test.sh
  e2e/live/testdata/rbac-error-step-1/namespace.yaml
  e2e/live/testdata/rbac-error-step-1/role-binding.yaml
  e2e/live/testdata/rbac-error-step-1/service-account.yaml
  e2e/live/testdata/rbac-error-step-2/config-map.yaml
  e2e/live/testdata/rbac-error-step-2/error-config-map.yaml
  e2e/live/testdata/rbac-error-step-2/inventory-template.yaml
Labels: area/live, customer, size/S

#1432 New pattern for setter comments
  internal/cmdsearch/putpattern_test.go
  internal/util/search/search.go
Labels: area/cfg, p1

#1451 Simplify setter creation experience, avoid kptfile dependency
  internal/cmdsearch/cmdsearch.go
  internal/cmdsearch/cmdsearch_test.go
  internal/cmdsearch/putpattern_test.go
  internal/util/search/search.go
Labels: area/cfg, p1

#1454 Tests for array search and type mismatch
  internal/cmdsearch/searchreplace_test.go
  internal/util/search/search.go
Labels: area/cfg, triaged

#1459 Best effort to derive setter pattern from regex
  internal/cmdsearch/putpattern_test.go
  internal/util/search/search.go
Labels: area/cfg

#1477 updating go-version to 1.15 across the board.
  .github/workflows/go.yml
  .github/workflows/verifyGuides.yml
Labels: area/devops, cleanup

#1472 Implement resolving regex capture groups
  internal/cmdsearch/cmdsearch.go
  internal/cmdsearch/cmdsearch_test.go
  internal/cmdsearch/putcomment_test.go
  internal/cmdsearch/searchreplace_test.go
  internal/util/search/search.go
  internal/util/search/search_test.go
Labels: area/cfg, ux impact

#1493 Put comment on sequence nodes
  internal/cmdsearch/putcomment_test.go
  internal/util/search/pathparser.go
  internal/util/search/search.go
Labels: area/cfg
